import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 9.5

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[shell]
program = "/usr/bin/tmux"

[window]
resize_increments = true
startup_mode = "Maximized"
