
[font]
size = 9.5

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/usr/bin/tmux"

[window]
resize_increments = true
startup_mode = "Maximized"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[terminal]
